Traceback (most recent call last):
  File "./cubes.py", line 89, in <module>
    main()
  File "./cubes.py", line 62, in main
    specification = Specification(spec)
  File "/home/rmbb/CUBES/squares/dsl/specification.py", line 120, in __init__
    self.data_frames['expected_output'] = read_table(self.output)
  File "/home/rmbb/CUBES/squares/dsl/specification.py", line 26, in read_table
    df = pandas.read_csv(path)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
